### ISSUE TITLE
Penilaian Progress-1 Projek STA1562 MDS

### ISSUE THREAD

**Issue by alfanugraha** [girlsMDS21/ManajemenDataStatistika_Project#1]
## **NILAI PROGRESS-1: 85**  

@girlsMDS21 

Beberapa catatan yang harus diperhatikan:
- Mohon ditambahkan **ulasan** tentang database yang ingin dikembangkan
- Cantumkan (unggah jika sudah ada) rencana data yang akan diperoleh dan digunakan pada projek ini
- Lampirkan **skema dan ER diagram**

**NB:**
Silahkan perluas wawasan cara penulisan di `markdown` melalui beberapa referensi berikut:
- https://www.makeareadme.com/
- https://dev.to/walternascimentobarroso/awesome-readme-44mf
- https://github.com/matiassingers/awesome-readme

**Comment by girlsMDS21** [comment]
maaf mas Alfa untuk ER Diagramnya sudah ada🙏
