### ISSUE TITLE
Penilaian Progress-2 ShinyDBApps

### ISSUE THREAD

**Issue by alfanugraha** [girlsMDS21/ManajemenDataStatistika_Project#2]
## **NILAI: 76**  

Catatan untuk penyempurnaan

> Masih terdapat redundansi data pada kolom komposisi, silahkan dinormalisasi. 

![k2produk](https://user-images.githubusercontent.com/5440894/224973022-b92333f9-04e8-417d-8c7f-8a56e5bff0dc.png)

> Tabel di atas juga akan lebih informatif jika dilakukan query join dengan beberapa tabel. Begitu juga pada halaman lain, kolom yang hanya berupa foreign key dapat dilakukan join dengan tabel lain agar informasi dapat tersampaikan dengan jelas.

![k2custskintype](https://user-images.githubusercontent.com/5440894/224973003-2d8f7d6b-3d12-4806-acd9-618949016421.png)

**Comment by Rekaagustia** [comment]
Baik, terimakasih ka alfa, akan segera kami perbaiki dan di update
